### ISSUE TITLE
Java apps cause repeat rule prompting

### ISSUE THREAD

**Issue by tomtastic** [jzdziarski/flockflock#8]
Java apps (at least the Java applet plugin for Safari) cause repeat rule prompt dialogs due to the changing temp/cache directory paths the process runs from,
is there a possibility of allowing/denying access based on parent process path instead ?

![ff_java_grok_problem](https://cloud.githubusercontent.com/assets/302127/17659724/5144fd32-62cc-11e6-9d80-5bb38cf3e106.jpg)

**Comment by jzdziarski** [comment]
Hello, thanks for the detailed information. This behavior should be fixed in 0.0.36a, so that it prompts you on Java itself, rather than the code it is running. Please confirm it's working like this now and I'll close out the issue. Thanks.

**Comment by tomtastic** [comment]
Tested this with a fresh .flockflockrc file and version 0.0.37, and I'm still having problems.

Parent is indeed recognised as java (/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java), with the application recognised in a path of /private/var/folders/.

Several invocations of the Java plugin result in multiple separate rules :
0 trcm:~ $ grep JuniperExt .flockflockrc
allow prefix "/Users/trcm/Library/Application Support/Juniper Networks/" "/private/var/folders/6c/93q04j8536v5kq_x480nh0p40000gn/T/tmp4924902956351586695JuniperExt via /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"
allow prefix "/Users/trcm/Library/Application Support/Juniper Networks/" "/private/var/folders/6c/93q04j8536v5kq_x480nh0p40000gn/T/tmp3793417959823057718JuniperExt via /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"
allow prefix "/Users/trcm/Library/Application Support/Juniper Networks/" "/private/var/folders/6c/93q04j8536v5kq_x480nh0p40000gn/T/tmp3992223355578858202JuniperExt via /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"

**Comment by jzdziarski** [comment]
I'm so sorry, I apparently fat-fingered the fix, and did a strncmp instead of a strncpy. Can you please try 0.0.38a and let me know if this has addressed the issue? If not, send me your email address so we can take this offline, and I'll try to work with you on a fix. Thanks.

**Comment by jzdziarski** [comment]
Was able to confirm 0.38a now resolves the issue. Closing this out. Feel free to re-open if there are any more problems with Java.
